name: hisobcheck
description: "Mebel sexi uchun moliyaviy ERP tizimi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  http: ^1.2.0
  encrypt: ^5.0.3 
  flutter_flip_card: any
  supabase_flutter: ^2.6.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  google_nav_bar: ^5.0.6
  excel: ^4.0.5
  pdf: ^3.11.1
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
